# Workflow derived from https://orchid00.github.io/actions_sandbox/testing-with-renev.html#testing-with-renev
on: 
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron:  '0 0 * * *'

name: renv-check

jobs:
  renv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
            r-version: '4.2.0'
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install libudunits2
        run: sudo apt-get install libudunits2-dev
      - name: Install gdal
        run: sudo apt install libgdal-dev
      - name: Install sodium
        run: sudo apt install libsodium-dev
      - name: Install libprotobuf
        run: sudo apt install libprotobuf-dev
      - name: Install renv latest
        run: Rscript -e "install.packages('renv', type = 'source')"
      - name: Fetch dependencies with renv
        run: Rscript -e "renv::restore()"